Map<String, String> ar = {
  'app_name': 'Crazy Food',
  'general_error': 'حدث خطآ ما',
  'no_internet':'لا يوجد اتصال بالانترنت',
  'home_tab': 'الرئيسية',
  'favourite_tab': 'المفضلة',
  'notification_tab': 'الاشعارات',
  'settings_tab': 'الاعدادت',
  'categories': 'أقسام التطبيق',
  'popular':'العروض الشائعه',
  'name': 'الاسم',
  'email': 'البريد الالكتروني',
  'birth_date': 'تاريخ الميلاد',
  'password': 'كلمه المرور',
  'sign_in': 'تسجيل الدخول',
  'sign_up': 'انشاء حساب',
  'signup_msg':'للاستمرارانشئ حساب باستخدام الايميل واكلمه المرور',
  'name_hint':'ادخل الاسم بالكامل',
  'email_hint':'ادخل البريد الالكتروني',
  'password_hint':'ادخل كلمه المرور',
  'empty': 'حقل فارغ',
  'phone': 'رقم الهاتف',
  'login_success': 'تم التسجيل بنجاح',
  'register_success': 'تم التسجيل بنجاح',
  'forget_password': 'نسيت كلمه المرور؟',
  'male': 'ذكر',
  'female': 'أنثي',
  'reset_password': 'استعاده كلمه المرور',
  'reset_password_desc': 'من فضلك ادخل البريد الالكتروني لاستعاده كلمه المرور',
  'level': 'مستوي',
  'next': 'التالي',
  'order_message':'اطلب اي منتج للحصول علي الخصم',
  'order_now':'اطلب الان',
  'order':'الطلب',
  'reviews':'التقييمات',
  'details':'التفاصيل',
  'location_map':'خريطة المكان',
  'shipping_details':'تفاصيل التسوق',
  'orders_details':'تفاصيل الطلب',
  'description':'الوصف',
  'your_order_placed':'Your Order was placed for delivery',
  'your_order_pending':'Your Order is pending for confirmation will confirmed whithin 5 minutes.',
  'your_order_confirmed':'Your Order is confirmed will deliver soon  whithin 5 minutes.',
  'your_order_processing':'Your Order is processing to deliver you on time.',
  'your_order_delivered':'Product deliver to you and marked as delivered by customer.',
  'delete_cart_item':'هل تريد حذف هذا العنصر من السلة؟',
  'checkout':'',
  'delete':'حذف',
  'cancel':'الغاء',
  'similar_products': 'المنتجات المشابهه'
};